name: Simple CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run echo command
        run: echo "Hello from GitHub Actions!"

      - name: Show file content
        run: cat test-actions.txt
  
